Το Umbrello είναι ένα ανοικτό εργαλείο για την δημιουργία σχεδιαγραμμάτων 
στην UML *Unified Modeling Language* και είναι ευρέως διαδεδομένο στις Unix-like πλατφόρμες. 
Είναι μέρος του KDE SC4 αλλα δουλεύει εξησου καλα και σε αλλα γραφικά περιβάλοντα.

Το Umbrello διαχειρίζεται όλους τους τύπους διαγραμμάτων της UML.
Μπορει να κανει reverse engineer σε κώδικα οπου ειναι γραμμένος σε C++, Pascal/Delphi, Python, Java καθώς
και να εισάγει XMI αρχεία δημιουργειμένα απο extension σε PHP ή Perl και να τα εξάγει σε διάφορες αλλες
γλώσσες Προγραμματισμού.Επίσεις δίνει την δινατότητα να διαμοιράσετε τα περιεχόμενα των μοντέλων σας 
εξάγοντας τα σε DocBook και XHTML. Αυτό βοηθά τα μέλη της ομάδας που δεν μπορούν να έχουν άμεση πρόσβαση 
στο Umbrello, ή σε περιπτώσεις όπου το περιεχόμενο μοντέλο θα πρέπει να δημοσιεύονται σε μια ιστοσελίδα.

Υποστηριζόμενες Γλωσσες Προγγραματισμού προς εξαγωγή
--------------------------
- ActionScript,Ada
- C#,C++
- D
- IDL
- Java,JavaScript
- Pascal,Perl,PHP,Python
- Ruby
- SQL
- Tcl
- XML Schema
--------------------------

Το Umbrello μπορει να βρεθει στην ιστοσελίδα http://uml.sourceforge.net[Umbrello]

Το Umbrello διατίθεται υπό την άδεια GPL.
