Το Nmap είναι ένα ανοικτό εργαλείο 
για την εξερεύνηση του δικτύου και τον έλεγχο της ασφάλειας.
Λειτουργεί ως σαρωτής ασφαλείας και χρησιμοποιείται για να ανακαλύψει 
κεντρικούς υπολογιστές και τις υπηρεσίες σε ένα δίκτυο υπολογιστών, 
δημιουργώντας έτσι ένα "χάρτη" του δικτύου.
Η λειτουργία του παρέχει στο χρήστη µια αναλυτική εικόνα, του προς ελέγχου δικτύου 
φανερώνοντας πιθανά προβλήματα και ελλείψεις ασφάλειας.

Βασικές Εντόλες
---------------------------------------------------------------------------
$ nmap -sT <Host ή IP> # βρίσκει τις ανοικτές TCP ports.
$ nmap -sU <Host ή IP> # βρίσκει τις ανοικτές UDP ports.
$ nmap -sP <Host ή IP> # βλέπει αν ο υπολογιστής ειναι ανοικτός.
$ nmap -sO <Host ή IP> # βρίσκει πια πρωτόκολλα υποστηρίζονται στο μηχάνημα
$ nmap -O  <Host ή IP> # βλέπει το λειτουργικό σύστημα στο μηχάνημα
---------------------------------------------------------------------------
Περισσότερα παραδείγματα υπάρχουν στον ιστότοπο: http://www.http://nmap.org/bennieston-tutorial/[Nmap Tutorial]

Η έξοδος από το Nmap είναι μια λίστα από σαρωμένους στόχους, με συμπληρωματικές πληροφορίες 
και κάθε μια εξαρτάται από τις επιλογές που χρησιμοποιήθηκαν. 
Μεταξύ των βασικών πληροφοριών είναι ο σημαντικός πινάκας των ports (interesting ports table). 
Αυτός ο πίνακας παραθέτει τον αριθμό θύρας και το πρωτόκολλο, το όνομα υπηρεσίας, και την κατάσταση. 
Ο πίνακας της θύρας μπορεί επίσης να περιλαμβάνει λεπτομέριες έκδοσης του λογισμικού όταν έχει ζητηθεί.

Το Nmap διατίθεται υπό την άδεια GPL.
