Το Nmap (Network Mapper) είναι ένα ανοικτό εργαλείο 
για την εξερεύνηση του δικτύου και τον έλεγχο της ασφάλειας.
Λειτουργεί ως σαρωτής ασφαλείας και χρησιμοποιείται για να ανακαλύψει 
κεντρικούς υπολογιστές και τις υπηρεσίες σε ένα δίκτυο υπολογιστών, 
δημιουργώντας έτσι ένα "χάρτη" του δικτύου.
Η λειτουργία του παρέχει στο χρήστη µια αναλυτική εικόνα, του προς ελέγχου δικτύου 
φανερώνοντας πιθανά προβλήματα και ελλείψεις ασφάλειας.

Το Nmap μπορει να βρεθει στιν ιστοσελίδα http://www.nmap.org[Nmap]

Βασικές Εντόλες
---------------------------------------------------------------------------
- nmap -sT <URL ή IP> βρεισκει τις ανοιχτες TCP ports.
- nmap -sU <URL ή IP> βρεισκει τις ανοιχτες UDP ports.
- nmap -sP <URL ή IP> βλεπει αν ο υπολογιστής ειναι ανοιχτός.
- nmap -sO <URL ή IP> βρίσκει πια πρωτόκολα υποστιρίζονται στο μηχάνημα
- nmap -O  <URL ή IP> βλέπει το λειτουργικό συστημα στο μηχάνημα
---------------------------------------------------------------------------

Περισότερα παραδείγματα υπάρχουν στον ιστότοπο του http://www.http://nmap.org/bennieston-tutorial/[Nmap Tutorial]

Η έξοδος από το Nmap είναι μια λίστα από σαρωμένους στόχους, με συμπληρωματικές πληροφορίες 
και κάθε μια εξαρτάται από τις επιλογές που χρησιμοποιήθηκαν. 
Μεταξύ των βασικών πληροφοριών είναι ο σημαντικός πινάκας των ports (interesting ports table). 
Αυτός ο πίνακας παραθέτει τον αριθμό θύρας και το πρωτόκολλο, το όνομα υπηρεσίας, και την κατάσταση. 
Ο πινάκας της θύρας μπορεί επίσης να περιλαμβάνει λεπτομέρειες έκδοσης του λογισμικού όταν έχει ζητηθεί έκδοση ανίχνευσης.

Το Nmap διατίθεται υπό την άδεια GNU.
