Το http://www.gnu.org/software/octave/[GNU Octave] είναι μία γλώσσα υψηλού επιπέδου ειδικού σκοπού με στόχο
την επίλυση αριθμητικών υπολογισμών. Παρέχει δυνατότητες για αριθμητική επίλυση γραμμικών και μη-γραμμικών προβλημάτων,καθώς και για την επίλυση άλλων αριθμητικών πειραμάτων. 
Επιπλέον παρέχει εκτεταμένες δυνατότητες γραφικών για την απεικόνιση των δεδομένων και τον χειρισμό τους. 
Το Octave χρησιμοποιείται συνήθως μέσα από μια διαδραστική διεπαφή γραμμής εντολών, αλλά μπορεί επίσης να χρησιμοποιηθεί για να γράψει μη-διαδραστικά προγράμματα. Το Οctave είναι παρόμοιο με το *Matlab*.

Μπορεί να χρησιμοποιηθεί για ανάλυση σήματος, στατιστική ανάλυση, ανάλυση
εικόνας, κλπ.


Το Octave διανέμεται υπό την http://www.gnu.org/software/octave/license.html[GPL]

Συγγραφή Προγραμμάτων
^^^^^^^^^^^^^^^^^^^^^

Χρησιμοποιείστε τον επεξεργαστή κειμένου για να
δημιουργήσετε ένα αρχείο πηγαίου κώδικα που μοιάζει με αυτό:

[source,scilab]
----
#
#  Print a fixed message to the screen.
#

  printf('Hello, world \n');

----

Αφού γράψουμε το κώδικα μας, τον αποθηκεύουμε με κατάληξη *.m*. Έπειτα μέσα
από την γραμμή εντολών του Octave τρέχουμε:

[source,octave]
--> hello           // το εκτελούμε

Γραφικό περιβάλλον Octave
^^^^^^^^^^^^^^^^^^^^^^^^^

To Octave δεν περιέχει στην μέχρι τώρα έκδοση 3.x κάποιο γραφικό περιβάλλον για την συγγραφή προγραμμάτων.
Παρόλα αυτά υπάρχουν πρόγραμματα τα οποία παρέχουν αυτήν την δυνατότητα, ένα από αυτά είναι το QtOctave 
το οποίο διανέμεται δωρεάν(GPL) και μπορούμε να το βρούμε από τους διαχειριστές πακέτων των διανομών Linux και 
στα Windows υπάρχει σε αυτόν τον https://sites.google.com/site/davidecittaro/software[σύνδεσμο]

Εναλλακτικές
^^^^^^^^^^^^

Παρόμοια λειτουργικότητα παρέχουν και τα πακέτα λογισμικού http://www.sagemath.org/[Sage]
και http://www.scilab.org/[Scilab] που διατίθενται υπό CeCILL άδεια που είναι συμβατή με τη GPL.
